spring.application.name=springbootwebtutorial
logging.level.root=DEBUG
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/adish/Documents/springbootwebtutorial/h2db/db/testdb
spring.datasource.username=Adish
spring.datasource.password=Adish123
spring.jpa.hibernate.ddl-auto=update